### ISSUE TITLE
Replace ID attribute with another name

### ISSUE THREAD

**Issue by shinxi** [predixdesignsystem/px-tooltip#34]
Currently px-tooltip uses id to indicate which element is the tooltip for. But looks currently px-tooltip allow duplicate ids. E.g.,
```jsx
<div>
    <div>
        <px-tooltip for="btn1" delay="50" tooltip-message="This is a tooltip A" orientation="auto">
        </px-tooltip>
        <button id='btn1'>Hover over me
        </button>
    </div>
    <div>
        <px-tooltip for="btn1" delay="50" tooltip-message="This is a tooltip B" orientation="auto">
        </px-tooltip>
        <button id='btn1'>Hover over me
        </button>
    </div>
</div>
```
Though two buttons have same id, but Tooltip will still work since current implementation is query at parent node scope.
```jsx
if(this.for && typeof(this.for) === 'string') {
        target = Polymer.dom(parentNode).querySelector('#' + this.for);
}
```
But id should be unique, right? From [w3c spec](https://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute),

> The id attribute specifies its element's unique identifier (ID). The value must be unique amongst all the IDs in the element's home subtree and must contain at least one character. 

One suggestion is to use another meaningful name instead of ```id```, such as ```tooltip-id```, or ```t-id```?

**Comment by benoitjchevalier** [comment]
I'm not sure I'm following you, are you asking for a way to have the tooltip work for several different element or wanting the tooltip not to work when several parent have the same ID?

**Comment by shinxi** [comment]
* Currently the tooltip works when several parent have the same ID, it's cool but same ID violate the w3c spec that id should be unique.
* So recommendation is use another API for tooltip reference, e.g., tooltip-id, in other words, the tooltip works when several parent have the same attribute tooltip-id. Below is code sample.
```jsx
<div>
    <div>
        <px-tooltip for="btn1" delay="50" tooltip-message="This is a tooltip A" orientation="auto">
        </px-tooltip>
        <button tooltip-id='btn1'>Hover over me
        </button>
    </div>
    <div>
        <px-tooltip for="btn1" delay="50" tooltip-message="This is a tooltip B" orientation="auto">
        </px-tooltip>
        <button tooltip-id='btn1'>Hover over me
        </button>
    </div>
</div>
```
Don't use ```id```, instead use ```tooltip-id```.

**Comment by benoitjchevalier** [comment]
Gotcha. I think the fact that it currently works with several elements having the same unique ID wasn't the intended behavior. The tooltip development happened in several phases and at first it would only work with a unique element, through an ID or being the parent. 

We then allowed to pass directly an element to it, and finally allowed to pass an array of element so that the tooltip would work for the whole array. The fact that it worked with several element having the same unique ID is a bit of a "happy coincidence".

Although you're making a fair point I don't think we'll be able to implement a change at this point in time (the whole team has been laid off last week). In your scenario I would advise to pass an array of element instead of using an id if you need multiple targets
